apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: general
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
      - name: mysql
        protocol: TCP
        port: 3306