apiVersion: v1
kind: Service
metadata:
 name: zookeeper-service
 namespace: zookeeper
 labels:
   app: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - name: client
      protocol: TCP
      targetPort: 2181
      port: 2181
