apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: zookeeper
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
      protocol: TCP
